server:
  port: 8100

zuul:
  routes:
    account-info-service:
     url: http://localhost:8084
    crop-info-service:
    url: http://localhost:8082
    dealer-info-service:
      url: http://localhost:8083
    farmer-info-service:
      url: http://localhost:8081
  # exclude Authorization from sensitive headers
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 1000000

spring:
  application:
    name: api-gateway-service


